-- public."Users" definition

-- Drop table

-- DROP TABLE public."Users";

CREATE TABLE public."Users" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"UserName" varchar(100) NOT NULL,
	"PasswordHash" text NOT NULL,
	"Salt" text NOT NULL,
	"Role" varchar(50) NOT NULL,
	"CreatedAt" timestamptz NOT NULL,
	CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);
CREATE UNIQUE INDEX "IX_Users_UserName" ON public."Users" USING btree ("UserName");